version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.7.5-management"
    ports:
      - "15672:15672"
      - "5672:5672"

  zipkin:
    image: "openzipkin/zipkin:2.9.3"
    container_name: zipkin
    links:
      - rabbitmq
    depends_on:
      - rabbitmq      
    environment:
      RABBIT_ADDRESSES: rabbitmq
    ports:
      - 9411:9411
    restart: on-failure
    
  prometheus:
    image: prom/prometheus:v2.2.0
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - sample-service-app
      - sample-client-app
    ports:
      - "9090:9090"
      
  grafana:
    image: grafana/grafana:5.0.1
    volumes:
      - "./monitor/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml"
      - "./monitor/grafana-dashboard.json:/etc/grafana/dashboards/default.json"
      - "./monitor/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yml"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus      

  sample-service-app:
    image: "sample-backend-app:0.0.1-SNAPSHOT"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq        
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    ports:
      - "8082:8080"

  sample-client-app:
    image: "sample-client-app:0.0.1-SNAPSHOT"
    links:
      - sample-service-app
      - rabbitmq
    depends_on:
      - rabbitmq        
    environment:
      SERVER_PORT: 8080
      LOAD_TARGET_URL: http://sample-service-app:8080
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672      
    ports:
      - "8080:8080"