# A sample demonstrating Spring Cloud Sleuth 2 with Zipkin

This is a sample set of apps that demonstrates how tracing information carries over from a client app to a service app and then gets aggregated into Zipkin UI

= Using Docker

First create the images for all apps using 

[source, bash]
----
./gradlew createDockerImage
----

and then

[source, bash]
----
docker-compose up
----

The application helper UI to send sample requests via the Client-App to the service app will be available at http://<dockerip>:8080

Zipkin UI will be at http://<dockerip>:9411
Graphana at http://<dockerip>:3000
and Prometheus at http://<dockerip>:3000


= Without Docker

== Start Zipkin

=== Start RabbitMQ first
[source, bash]
----
rabbitmq-server
----

=== Start Zipkin integrated with RabbitMQ:

[source, bash]
----
curl -sSL https://zipkin.io/quickstart.sh | bash -s
----

=== Once Zipkin jar is downloaded, run it this way:

[source, bash]
----
RABBIT_ADDRESSES=localhost java -jar zipkin.jar
----

== Client App
[source, bash]
----
./gradlew -p applications/sample-client-app clean bootRun
----

== Sample Service App
[source, bash]
----
./gradlew -p applications/sample-service-app clean bootRun
----

= Testing
Assuming that https://httpie.org/[httpie] is installed

[source, bash]
----
http POST 'http://localhost:8080/passthrough/messages' id="1" payload="one"   delay="1000"
----

OR with CURL

[source, bash]
----
curl -X "POST" "http://localhost:8080/passthrough/messages" \
     -H "Accept: application/json" \
     -H "Content-Type: application/json" \
     -d $'{
  "id": "1",
  "payload": "one",
  "delay": "1000"
}'
----

Trace information should get logged into the console and end up in Zipkin UI available at http://localhost:9411


= Generating load

A gatling based load can be sent to the app using:  
[source, bash]
----
./gradlew -p applications/load-scripts  -DTARGET_URL=http://localhost:8080 -DSIM_USERS=50 gatlingRun
----