apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-client-app-v1
  labels:
    app: sample-client-app-v1
    visualize: "true"
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-client-app
  template:
    metadata:
      labels:
        app: sample-client-app
        version: v1
        visualize: "true"
    spec:
      containers:
      - name: sample-client-app
        image: sample-client-app:0.0.1-SNAPSHOT
        env:
        - name: VERSION
          value: "1.0"
        - name: LOAD_TARGET_URL
          value: http://sample-service-app-service:8080
        ports:
        - name: http
          containerPort: 8080