apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-backend-app-v1
  labels:
    app: sample-backend-app-v1
    visualize: "true"
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-backend-app
      version: v1
  template:
    metadata:
      labels:
        app: sample-backend-app
        version: v1
    spec:
      containers:
      - name: sample-backend-app
        image: bijukunjummen/sample-backend-app:0.0.2-SNAPSHOT
        env:
        - name: VERSION
          value: "1.0"
        - name: SERVER_PORT
          value: "8080"
        ports:
        - name: http
          containerPort: 8080