apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-service-app-v1
  labels:
    app: sample-service-app-v1
    visualize: "true"
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-service-app
  template:
    metadata:
      labels:
        app: sample-service-app
        version: v1
        visualize: "true"
    spec:
      containers:
      - name: sample-service-app
        image: sample-service-app:0.0.1-SNAPSHOT
        env:
        - name: VERSION
          value: "1.0"
        - name: SERVER_PORT
          value: "8080"
        ports:
        - name: http
          containerPort: 8080