---
apiVersion: v1
kind: Service
metadata:
  name: sample-client-app-gateway
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: sample-client-app 
      prefix: /passthrough/
      rewrite: /passthrough/
      service: knative-ingressgateway.istio-system.svc.cluster.local 
      host_rewrite: sample-client-app.default.example.com
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
    service: ambassador
